const items=[{e:'🍓',n:'딸기'},{e:'🥛',n:'우유'},{e:'🍦',n:'아이스크림'},{e:'🐟',n:'물고기'},{e:'🍪',n:'과자'},{e:'🧃',n:'주스'},{e:'🍎',n:'사과'},{e:'🧀',n:'치즈'},{e:'🍌',n:'바나나'}];
const customers=['🐧','🐧','🐧','🐧']; let score=0,round=0,order=[],soundOn=true,locked=false,acc='';
const $=s=>document.querySelector(s), products=$('#products'),customer=$('#customer'),msg=$('#message'),delivery=$('#delivery');
function shuffle(a){return [...a].sort(()=>Math.random()-.5)}
function speak(t){if(!soundOn||!('speechSynthesis'in window))return;speechSynthesis.cancel();let u=new SpeechSynthesisUtterance(t);u.lang='ko-KR';u.rate=.92;speechSynthesis.speak(u)}
function renderProducts(){products.innerHTML='';shuffle(items).slice(0,6).forEach(it=>{let b=document.createElement('button');b.className='product';b.innerHTML=`${it.e}<span class="light">●</span>`;b.onclick=()=>choose(it,b);products.appendChild(b)})}
function newRound(){locked=false;delivery.textContent='';round++;if(round>5){finishSet();return}$('#round').textContent=Array.from({length:5},(_,i)=>i<round?'●':'○').join(' ');renderProducts();let visible=[...products.children].map(b=>b.textContent.trim().replace('●','').trim());let count=score>=6&&Math.random()<.45?2:1;order=shuffle(visible).slice(0,count);$('#orderIcons').textContent=order.join(' + ');customer.classList.remove('happy');msg.textContent='👀  →  👆';speak(count===1?'펭귄이 원하는 것을 찾아 주세요':'펭귄이 두 가지를 주문했어요');randomWeather()}
let picked=[];
function choose(it,b){if(locked)return;b.classList.add('shake');setTimeout(()=>b.classList.remove('shake'),350);if(!order.includes(it.e)){msg.textContent='🐧 🤔  다시!';speak('음, 다시 찾아볼까요?');return}if(picked.includes(it.e))return;picked.push(it.e);delivery.textContent=it.e;delivery.className='delivery drop';setTimeout(()=>delivery.className='delivery',800);if(order.every(x=>picked.includes(x))){locked=true;score++;$('#stars').textContent='⭐ '+score;customer.classList.add('happy');msg.textContent='🎉 ⭐';speak('와! 맞았어요!');setTimeout(()=>{picked=[];showReward()},850)}else{speak('좋아요! 하나 더 찾아볼까요?')}
}
function showReward(){if(Math.random()<.28){miniGame();return}$('#celebrateFace').textContent='🐧'+acc;$('#celebrateText').textContent='⭐ '+score;$('#celebrate').classList.remove('hidden')}
$('#nextBtn').onclick=()=>{$('#celebrate').classList.add('hidden');newRound()};
function finishSet(){round=0;$('#celebrateFace').textContent='🐧'+acc;$('#celebrateText').textContent='🏆 ⭐ '+score;$('#celebrate').classList.remove('hidden');speak('멋져요! 펭귄 자판기 최고예요!')}
function randomWeather(){let r=Math.random();$('#scene').classList.remove('night');$('#weather').textContent=r<.35?'☀️':r<.7?'❄️':'🌙';if(r>.9)setTimeout(()=>snowEvent(),900)}
function snowEvent(){if(locked)return;locked=true;$('#machine').classList.add('snowed');msg.textContent='❄️ 👆 〰️';speak('앗 눈이 쌓였어요. 자판기를 손가락으로 닦아 주세요');let cover=$('#snowCover'),moves=0;let wipe=e=>{moves++;cover.style.opacity=Math.max(.05,1-moves/8);if(moves>=8){cover.removeEventListener('pointermove',wipe);$('#machine').classList.remove('snowed');cover.style.opacity=1;locked=false;msg.textContent='✨ 🐧 ✨';speak('깨끗해졌어요!')}};cover.addEventListener('pointermove',wipe)}
function miniGame(){let ov=$('#miniOverlay'),box=$('#miniGame');ov.classList.remove('hidden');let type=Math.floor(Math.random()*2);if(type===0){$('#miniTitle').textContent='🪙 👀';box.innerHTML='<div class="coinField"></div>';let f=box.firstChild;for(let i=0;i<5;i++){let c=document.createElement('button');c.className='coin';c.textContent=i===3?'🪙':'❄️';c.style.left=(8+Math.random()*75)+'%';c.style.top=(5+Math.random()*65)+'%';if(i===3)c.onclick=()=>{speak('동전을 찾았어요!');ov.classList.add('hidden');newRound()};f.appendChild(c)}speak('떨어진 동전을 찾아 주세요')}else{$('#miniTitle').textContent='🐟 💨';let choices=shuffle(['🐟','🍪','🧃']);box.innerHTML='<div class="miniGrid"></div>';choices.forEach(x=>{let b=document.createElement('button');b.textContent=x;b.onclick=()=>{if(x==='🐟'){speak('물고기를 잡았어요!');ov.classList.add('hidden');newRound()}else{speak('다시 찾아봐요')};box.firstChild.appendChild(b)});speak('도망간 물고기를 잡아 주세요')}}
$('#dressBtn').onclick=()=>$('#dressOverlay').classList.remove('hidden');$('#dressOverlay .close').onclick=()=>$('#dressOverlay').classList.add('hidden');document.querySelectorAll('.dressGrid button').forEach(b=>b.onclick=()=>{acc=b.dataset.acc;$('#accessory').textContent=acc;$('#dressOverlay').classList.add('hidden');speak('멋지게 꾸몄어요')});
$('#helpBtn').onclick=()=>{msg.textContent='👉 '+order.join('  ');speak('이 그림과 같은 것을 찾아 주세요')};$('#soundBtn').onclick=()=>{soundOn=!soundOn;$('#soundBtn').textContent=soundOn?'🔊':'🔇'};
newRound();
